### ISSUE TITLE
Modify browser notifications to show which file was uploaded

### ISSUE THREAD

**Issue by naveenkumarsangi** [NITDgpOS/PiZilla#71]
The current notification schema only shows a vague message like this.

![screen shot 2017-12-23 at 1 19 43 pm](https://user-images.githubusercontent.com/17202890/34318068-f93ea31a-e7e3-11e7-9b48-ba691f35ccff.png)

![screen shot 2017-12-23 at 1 22 26 pm](https://user-images.githubusercontent.com/17202890/34318085-7a9a54ea-e7e4-11e7-92d2-2d6286f0fe44.png)

![screen shot 2017-12-23 at 1 24 21 pm](https://user-images.githubusercontent.com/17202890/34318092-a0e89a9e-e7e4-11e7-80db-283bf1ccec95.png)

Which isn't very helpful. It should rather show what was uploaded and preferably, the logo of PiZilla too to indicate where the notification was received from.

**Comment by nkprince007** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by nkprince007** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by JayjeetAtGithub** [comment]
Hi nkprice007, i want to work on this
